spring:
  datasource:
    url: jdbc:mysql://192.168.42.131:3306/spring_vue_mall?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
server:
  port: 8888


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
shiro-redis:
  enable: true
  redis-manager:
    host: 192.168.42.131:6379
markerhub:
  jwt:
    #加密的盐
    secret: 1a2b3c4d5e
    #
    expire: 604800
    header: Authorization
alipay:
  appId: 9021000135634088
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCFlY7rY+DCmNv4+iA+hNxUFZCMFOfK9P9mGJrnM3H12wzDS1YW0EFMAsJTw7Wsqa8sVIe5JN7he8tNHUUz9RF83bHvljF/km/qGV32mFFyVI59XCQpQHjU2IXP5xmFz0vRJZd4p7gaVqY7C/TLwFD/AS/vFd0KR/rBNdGIyzno+JAhmbt+3z6jv+Ck0OR8/vNYoSuwySwI+FS1zDl6mnJplMEnQvanQtS5TPrm30GVLf5Y2Y0EFsPNS2TY6u1WQMs6FMJQIRnEzMl2t36DcmZ8rxnjuknUozMrVscGCeNIoBzI7BdwouziE3vVH6FcYxfhmcgqt8SopB2wopo8IP7jAgMBAAECggEAUpmkAhGETU/P1Sh0/7OPub6L3tKecXUE59CXGBdLhEaqoafX18t2VNXv63O8xsM1uieatPUDjFHL6CcNP49t/NPozskEWmnmIc8FtxGAaz21zfZHtepTzOkF9QRlV8RSkUS5YLX0tPSXXTOLbuHAM648QY43W8AeYZIxunBPoqoJTZ2gDipKNVIGghRKCiciQri9SaUvajKWIv6kCrjf5UDRmP5TSV+jd485l1Xt9s6lVYQEm3w8qLLRHnMZTLfOaryrmOnvS2JBc45vU+/bc/tFi8Z0hi3X9L6G72QTsuHTqQ7pkTiyRAbP2eFqUCUnrleREhvWsNh2BrKkYloZIQKBgQDTohIksq1U6DeYJKSZFuUxUs025ut0aaaOpUooiD8V6GCDruZXdiVToYlJTV2M8UED9H6amcs2zHxARkgYjL+0SNGU0HZRvoRdLUjqKYSWBnDI1r7LB1ZjauESeUOoVK2ZuDeZrHlq4pQKSQj8VvGH/O9ggtoICaUvurbw7RxcRQKBgQChlsIz2Hx0QnEjTdhGQPkblu3BejpYvcGC0FHo3ItBOd1/vT7abJrvJPAVhbLlZ6FL7xlCa4CwxzL+j2zvHlm53FhwgIQ+rehR3ot+h3gDofEI0A8TrskSJG714iOhUvlra6g4H8XtDuE8Oa2mmnVHGLMABF7BURjP5VcCgHqlBwKBgQCGIPHe0F+KsKKLiq3HWPtph1EIutH/tfYZ8ihOCAvzlpOU4gSa6gY+OuMH0kC4Uy8hkpOq6E4jLPaSxfhrlsjpOj2aU4SpylWZuFm+DxI5A1v37iJ+Cuh1mgeL7c8zoHdmNZsHiohpdbDd0+weAfySc3xDbqtA7NwEpBHOIHkZAQKBgCfhnJbNNJJBH8lV2i4ktRbRHmclMqdaVhtiLQUrAZecn4V6gLvKGEczt6moMOobtJyYK4TQIZf/4h8f6QPvWrfboVxK69jIdVFXethEuSM0YdgJ+d6iwe+fXF+Fa8PSRcr0bDVF6kTC6mZB2hEHiDB+8Rbs/TH7QQN2mA3/BcYbAoGBAMfrB2u3MJJ7obBF7zMNK3ZWxCWDOcYM3lZVhrpcRcPWFv7CCTQ8eO+zw+om3dMy0vrez9bzcdF16wyZcn6R63n/m5mW+n4CQOA0Wq2fOy+m8xUXCRfg7+L+23IqGzHw8nFcL+lvjxe1MjwfDMJ87fuUFd7/vAfwO+JBAzaiC0Qf
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3D+QyOP18jxtgE1+mwKdM2RoswEhFHsxPZYauZpyeLUIGIZ38EnlDp+itisMVWGWPQV8jfBimlBBoiKl8LyzYypS4dCYNkqb1O/3aLf6Va7zkzRwS9gOBgKnPpzwGy0b1G5x/rVfRESJ8fmdBvv/GM2fq55rhIteKlBHFj50r4IVFZpogKAOoSeikX7gCq4UQXeXgj5ogjbIXzvIi2KeFpbFoyoSN6+YlWZ+AI+yKakj4KslQBNtMiIyO6T4BWwmw9n+ttbIjJehbDvK/oUNsBpOIgpasZ7GuLK6Yl+5pEffv4Sd8ZmPoX4NoZZAWzrECA3h/NJkUGAn26UOGXTV9QIDAQAB
  notifyUrl: http://localhost/alipay/notify

fabric:
  certificatePath: src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  privateKeyPath: src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  tlsCertPath: src/main/resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  channel: mychannel
